### ISSUE TITLE
[Integration Test] Alert action

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle#1000]
### Scenarios:

1. Shows an alert on the screen with just a message HARDCODED and via EXPRESSION
2. Show an alert on the screen with just a title and message HARDCODED and via EXPRESSION
3. Show an alert on the screen with an action and check if the action was performed (you can put it to run another alert)
4. Show an alert with customized text on the button.

- [x] Android
- [x] iOS
- [x] WEB

**Comment by carlossteinzup** [comment]
we have updated the Scenarios to better to the tests in all fronts. 
We have removed the scenario that requested to test a Alert message with only the title since:
- The front in WEB does not have a Title set through the Alert Beagle Action
- It is not possible to set just a Title in an Alert since the MESSAGE attribute is mandatory.
