### ISSUE TITLE
EPIC - Global Context

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#123]
### Describe the problem
We have some situations here is common in applications, like so:
1. Save form steps locally and in the last step send all data to backend.
2. Do something in another screen and save this data locally to get the information in the previous screen. Ex.: Add a product to cart and when user back to home screen the cart counter is incremented.

### Expected behaviour
Save some data in a global context and retrieve in a local context.

- [x] iOS: #587
- [ ] Android: #538
- [x] Web: https://github.com/ZupIT/beagle-web-core/pull/180

**Comment by Tiagoperes** [comment]
### Definition

The GlobalContextAPI is a public API exposed by Beagle so that it is possible to access the global context inside the application code. The following code defines the interface of this API.

```typescript
interface GlobalContextAPI {
  get: (path?: string) => any,
  set: (value: any, path?: string) => void,
  clear: (path?: string) => void,
}
```

The `path` in the interface above works the same way as the `path` in the action `setContext`.

- **`GlobalContextAPI.get`**: recovers a value in the global context. If the parameter `path` is not specified, the entire value of the global context is returned. Otherwise, only the value corresponding to the path is returned.
- **`GlobalContextAPI.set`**: sets a value in the global context. If the parameter `path` is not specified, `value` will be assigned as the value of the global context, i.e. the entire global context will be replaced by the new value. Otherwise, only the value corresponding to the path will be replaced. **This function also updates the view so it reflects any modification to the global context.**
- **`GlobalContextAPI.clear`**: removes an entry from the global context. If the parameter `path` is not specified, the entire global context will be cleared, i.e. the global context will be set to null. Otherwise, if the global context is an object, the key corresponding to the path will be removed. If the global context is an array, the position corresponding to the path will be set to null. **This function also updates the view so it reflects any modification to the global context.**

The global context is accessed by the server driven view through a special context called "global". It is not allowed to name a common context as "global", if it happens, a warning should be given to the developer, because it won't work properly.

To set a value in the global context through a server driven view, the action `setContext` with the `contextId` "global" should be used. We must modify the `setContext` action to verify if the `contextId` is "global". If it is, we should set a value in the global context and not in a context defined by the own view.

**Observations:**
- `GlobalContextAPI.set` and `GlobalContextAPI.clear` should guarantee the values will be updated in the view.
- The global context is alive as long as the application is alive. The application closes, the global context is cleared.
- It is the developer's responsibility to set and clear the values in the global context. For instance, to logout a user, all its data should be removed from the global the context by using `GlobalContextAPI.clear`.
-  If the developer wants to persist the global context locally and make it accessible throughout multiple executions, it might be a difficult feature to implement in iOS.

### Examples

> Attention: in the examples below we consider the implementation for Beagle Web, where the GlobalContextAPI will probably be implemented in `beagleService.globalContext`.

**Setting a value in the global context inside the application code:**

```typescript
beagleService.globalContext.setValue({
  name: 'Fulano da Silva',
  cpf: '000.000.000-00',
  balance: 58.9
}, 'user')
```

From now on, the server driven views can make reference to `@{global.user}`.

**Referring to the global context in a server driven view:**

```json
{
  "_beagleComponent_": "text",
  "text": "Hello @{global.user.name}, your current balance is @{global.user.balance}."
}
```

**Setting a value in the global context via a server driven view:**

```json
{
  "_beagleComponent_": "button",
  "onPress": [
    {
      "_beagleAction_": "setContext",
      "contextId": "global",
      "path": "user.balance",
      "value": 97.87
    }
  ]
}
```
