### ISSUE TITLE
Disable Cache

### ISSUE THREAD

**Issue by victorrabelozup** [ZupIT/beagle#1274]
## Use case
When trying to disable cache there is an inconsistency between the platforms.
In iOS instead of setting a feature flag independent from the cache manager object, the way to do it is to set the cache object to null.

## Proposal
Equalize all the platforms to have the same behavior as the iOS.

**Comment by Tiagoperes** [comment]
I don't know about Android, but we don't have anything equivalent to "Cache Manager" in Beagle WEB. I also don't think it is worth refactoring the code if the cache can be disabled in some other way.

I Beagle WEB, the cache can be disabled with `strategy: network-only`.

We do have an object used for data persistence and it is mostly used for caching, but not necessarily only cache. If the user passes the configuration `storage: new MyUselessStorageImplementation()`, where `MyUselessStorageImplementation` doesn't implement any of the `BeagleStorage` interface, the cache will be effectively disabled. We could it make so `storage: null` has the same behavior as ``storage: new MyUselessStorageImplementation()`. Maybe it would become more simmilar to iOS, but, as said before, not exactly the same, since it is responsible for any persistent storage.
