### ISSUE TITLE
ListView scrollIndicator

### ISSUE THREAD

**Issue by luisgustavozup** [ZupIT/beagle#1287]
## Description:
ListView has the default `scrollIndicator` enabled, it does not have an attribute to change the state.

## Solution:
Create a new attribute to enable and disable the `scrollIndicator`.
Name suggestion **scrollIndicatorEnabled**.

```
    public var context: Context?
    public let onInit: [RawAction]?
    public let dataSource: Expression<[DynamicObject]>
    public let key: String?
    public let direction: Direction?
    public let template: RawComponent
    public let iteratorName: String?
    public let onScrollEnd: [RawAction]?
    public let scrollEndThreshold: Int?
    public let scrollIndicatorEnabled: Bool?
    public var widgetProperties: WidgetProperties
```

## Example screenshot:
<img width="364" alt="Screen Shot 2021-01-07 at 15 37 14" src="https://user-images.githubusercontent.com/59032921/103931686-76814d00-50ff-11eb-8d1b-be7efc17343e.png">

**Comment by Tiagoperes** [comment]
I remember I said once this wouldn't make much sense in Beagle WEB, because in a web page, the UI wouldn't allow the user to scroll the content if no scroll bar is visible. But, considering Beagle WEB can also be used as WEB Views inside apps, it does make sense to be able to hide these bars.

Suggestions:
- `scrollIndicator: 'visible' | 'hidden'`
- `isScrollIndicatorVisible: boolean`

**Comment by luisgustavozup** [comment]
I talked to the android people and we used the parameter name as `isScrollIndicatorVisible: boolean`

**Comment by Tiagoperes** [comment]
We still have to do this for web
