### ISSUE TITLE
How can I execute an action passed in as param of a custom action on Android/iOS?

### ISSUE THREAD

**Issue by hoangnv11** [ZupIT/beagle#1508]
## Use case

Hi guys,
I open this issue with a view to asking if we can execute an action passed in as param of a custom action on Android/iOS?
I'm creating a custom action called **CapturePhoto** and I want to pass in another custom action so that I can execute it if a condition is met or an event is triggered.
In the context of a custom widget, I know I can achieve it using the method **ServerDrivenComponent.handleEvent()** (on Android), but I don't know how to achieve the same in the context of a custom action?

Thank you all!

**Comment by Tiagoperes** [comment]
Hi @hoangnv11, this is missing in our documentation and creating examples for this is in our radar.

While the documentation is not ready, it is a good idea to check how our own default actions have been implemented. I think they will suffice to give you what you need to make your own custom action implementation.

Here are some actions that trigger events, i.e. that can accept other action as parameters:

- [Alert (onPressOk)](https://github.com/ZupIT/beagle/blob/master/android/beagle/src/main/java/br/com/zup/beagle/android/action/Alert.kt) 
- [Confirm (onPressOk, onPressCancel)](https://github.com/ZupIT/beagle/blob/master/android/beagle/src/main/java/br/com/zup/beagle/android/action/Confirm.kt)
- [SendRequest (onSuccess, onError, onFinish)](https://github.com/ZupIT/beagle/blob/master/android/beagle/src/main/java/br/com/zup/beagle/android/action/SendRequest.kt)
- [Condition (onTrue, onFalse)](https://github.com/ZupIT/beagle/blob/master/android/beagle/src/main/java/br/com/zup/beagle/android/action/Condition.kt)

If these examples are not enough, please tell us so we can provide a better example for your specific situation.

Just an observation, You're talking about actions that execute depending on a condition, Beagle offers a [default action called "condition"](https://docs.usebeagle.io/v1.6/api/actions/condition/), it can be used exactly for that, maybe it can help you achieve the result you want.

**Comment by hoangnv11** [comment]
Yeah I already know actions you mention above.
Sorry if my way of expression causes any ambiguity and misunderstanding.
The problem I'm facing now is not how to trigger event, it's how to run a custom action wrapped in another custom action.. I think I should include some code snippets here to make my question clearer.

Firstly, I have this action:
```
@RegisterAction
data class CapturePhoto(
    val actionOnSuccess: Action,
    val actionOnFailure: Action? = null
) : Action
```
and the following action, which is another custom action:
```
@RegisterAction
data class ToastAction(val message: String) : Action
```
From Beagle BFF, I'll use them as follows:
```
CapturePhoto(actionOnSuccess = ToastAction("Capture photo successfully!"))
```
=> It means that, on client, the CapturePhoto action will help me open camera and capture a photo. I can know if a photo is captured successfully or not. If successful, I would like to run the ToastAction to toast a message indicating that users have captured a photo successfully.

To be more specific, my code on Android will go like this:
```
@RegisterAction
data class CapturePhoto(
    val actionOnSuccess: Action,
    val actionOnFailure: Action? = null
) : Action {
    override fun execute(rootView: RootView, origin: View) {
        // how to run actionOnSuccess here?
    }
}
```
@Tiagoperes I know you specialize in Web, not Android. So, can you mention someone in Beagle team who works on Android to help me answer this question?
Thank you very much! :D

**Comment by hoangnv11** [comment]
Furthermore, I'm also curious to know how to use a callback in a custom action so that in the context of that action, I can return a value from native to Beagle?

**Comment by Tiagoperes** [comment]
@hoangnv11 maybe you didn't understand my answer. Have you checked my links? I'm not telling you to use any of those actions, what I'm saying is that those actions are very similar to the action you're trying to create and you should use them as a basis for writing yours.

The action `SendRequest`, for instance, has the parameters `onSuccess` and `onError`, which are other actions. It is very similar to the action you're trying to implement, so why not check its source code and do something similar? The links I posted in the previous answer are the code that implements each of those actions, **it is not the documentation**, you can use them as your examples.

Concerning your second question "how to use a callback in a custom action so that in the context of that action, I can return a value from native to Beagle?". We also do this in the action `SendRequest`, when executing the sub-action provided by the parameter `onSuccess`, we tell Beagle to put in the context the result of the request. You can use this example to achieve something similar and communicate data from your application to Beagle.

Again, I'm not telling you to use the action `SendRequest`. What I'm telling you is that the implementation of `CapturePhoto` will be extremely similar to the implementation of `SendRequest`, so you can use our source code as an example.

**Comment by hoangnv11** [comment]
Oh now I understand your answer.
That's my mistake. I've read the source code of the action above but I don't get your idea. Now I get it already.
I'll try to apply it to my custom actions.
Thank you so much for your enthusiastic support! @Tiagoperes
