### ISSUE TITLE
Define a branch nomenclature as default

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/beagle#1577]
Ref: https://github.com/ZupIT/charlescd-docs/issues/5

**Comment by Tiagoperes** [comment]
Hi, today we have 12 repos related to Beagle, only 2 of them have "main" as the main branch name. All others are named "master". So, it would be much easier for us to rename these two branches to "master" instead of the opposite.

Anyway, we never had a problem with these 2 repos that have the main branch name as "main" instead o "master". Why is this a problem? You said it's vital the main branch name is the same across all open source repos in the same organization, why is it vital? After discussion, we couldn't think of any good reason to do this. Can you elaborate for us why this is a real problem?
