### ISSUE TITLE
PageView make the parameters of viewPager's onPageScrolled method available

### ISSUE THREAD

**Issue by josenetozup** [ZupIT/beagle#1634]
## Use case
Animate view according to viewPager offset

```kotlin
override fun onPageScrolled(
                position: Int,
                positionOffset: Float,
                positionOffsetPixels: Int,
            ) {
            }
```
### Problem
The positionOffset callback is not available to be used in BFF

**Comment by Tiagoperes** [comment]
Please, elaborate the problem.

**Comment by josenetozup** [comment]
> Please, elaborate the problem.

In BFF, there is no callback for this method

**Comment by matheusribeirozup** [comment]
As the listener for PageView through offset generates constant and consecutive triggers, its impracticable to apply this behavior to the Beagle because it would bring performance problems. We recommend using a custom PageView, this way the view itself would take care of these callbacks without negative impact on performance.
