### ISSUE TITLE
GridView doesn't have direction property

### ISSUE THREAD

**Issue by minmon98** [ZupIT/beagle#1640]
GridView has released in beagle version 1.8.1. But I realize that it has not supported direction property yet, so I could not set the direction VERTICAL or HORIZONTAL for gridview. Could you consider to support this in the next version ?.

Thank you

**Comment by Tiagoperes** [comment]
Hello @minmon98, please take a look at the image below: 

![ink](https://user-images.githubusercontent.com/1119029/122652253-35608080-d114-11eb-9195-889fd230992f.png)

If I understand correctly, you're asking us to add a "rows" attribute, like sketched in the image above? Is that it?

**Comment by minmon98** [comment]
@Tiagoperes yeah, it's exactly what I request

**Comment by Tiagoperes** [comment]
It makes sense, we'll do this for version 1.9.

## Specification
Add `direction` and `spanCount` to the GridView. Deprecate `numColumns`. When `numColumns` is passed instead of `direction` and `spanCount`, consider `direction = "vertical"` and `spanCount = numColumns`. If all are passed, ignore `numColumns`.

## Tasks
- [ ] Android
- [ ] iOS
- [ ] React
- [ ] Angular

**Comment by uziasferreirazup** [comment]
Release 1.9 publish to see how to works new API to use GridView check this link: https://docs.usebeagle.io/v1.9/api/components/layout/gridview/

**Comment by minmon98** [comment]
@Tiagoperes @uziasferreirazup I have just checked this version. It's really amazing, big thanks for your support
