### ISSUE TITLE
[ANDROID] - Navigate.PushView deixa tela branca.

### ISSUE THREAD

**Issue by danilorangelmg** [ZupIT/beagle#1797]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Beagle release to make sure your issue has not already been fixed: https://github.com/ZupIT/beagle/releases

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Criar uma tela com qualquer formato
2. Utilizar  Navigate.PushView(route = Route.Remote("\newScreen")) - chamando uma nova tela
3. Esperar a nova tela carregar
4. Clicar no botao voltar da toolbar
5. A tela aparecerá em branco.

## Expected Results
Describe what you expected to happen.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by carlossteinzup** [comment]
Hello @danilorangelmg , thanks again for raising an issue.
Could you please share a little bit more details about your context please?
* What Beagle Version are you using?
* The toolbar backbutton you refer is the default backbutton from the native android toolbar?
* Or did you build a customized toolbar that calls another Beagle Action?

**Comment by carlossteinzup** [comment]
Hello @danilorangelmg  , I have tested this behaviour you described in the last two versions (1.10 and 1.9) and I could not reproduce the issue. The previous activity was displayed in my tests.

We recommend that both the front and back version be the same. Also, the backbutton functionality on the toolbar is not controlled by Beagle, being that triggered by the Android system itself.

This issue has been closed due to the reason: Could not reproduce the bug. It can be reopened if new information appears
