### ISSUE TITLE
Difficult to change HTTP headers with NetworkClient

### ISSUE THREAD

**Issue by LG95** [ZupIT/beagle#24]
**Problem**
I need to add header to HTTP request to call circles in Charles. And this is not easy to implement.
Example code:
```swift
class BeagleConfig {

    static let dependencies = BeagleDependencies()
    static let client = NetworkClientDefault(dependencies: dependencies)
    static func config() {
        client.httpRequestBuilder.additionalHeaders = ["x-circle-id":"578640d5-50af-41d4-817c-4639f80c207d"]
        dependencies.networkClient = client
        Beagle.dependencies = dependencies
    }
}
```

**Solution**
A possible solution is adding an interception on network layer to abstract this problem.

**Comment by gabcoelho** [comment]
After discussing this with the rest of the iOS team we decided to close this issue since it didn't make a lot of sense for Beagle to have an interceptor on NetworkClient.

**Comment by theffc** [comment]
Just some more context:

To solve this problem of appending http headers to arbitrary requests, we would need to add some functionality (e.g UrlRequest interceptor) to the network layer that actually handles http logic. 
We already provide a default implementation of this layer with basic functionality (builds url requests, check some status code, etc). But we think this layer will probably be customised by our users, since it can vary significantly depending on app's requirement (like authentications, network protocols and so). So, we think that spending time improving this default implementation will not really add value to our product on the long run.
