### ISSUE TITLE
EPIC - Context Operations

### ISSUE THREAD

**Issue by tuliopereirazup** [ZupIT/beagle#503]
## Use Case
As a developer I wanted to use some basic operations like _equality_, _addition_, and _conditions_ to make more complex screens via backend. That way, my components wouldn't need to implement those logics inside them.

Example1: When clicking on a Button, it could change the current value of Context to the value itself plus one
`@{sum(counter, 1)}`
Example2: When text field/input changes, I wanted to trigger some basic validation to see if a button should be enabled. 

## Possible Solution after our discussions

- Basic example of a Counter in json:
```json
{
  "_beagleComponent_": "beagle:container",
  "context": {
    "id": "counter",
    "value": 0
  },
  "children": [
    {
      "_beagleComponent_": "beagle:text",
      "text": "@{counter}"
    },
    {
      "_beagleComponent_": "beagle:button",
      "text": "increment",
      "onPress": [
        {
          "_beagleAction_": "beagle:setContext",
          "contextId": "counter",
          "value": "@{sum(counter, 1)}"
        }
      ]
    }
  ]
}
```

- a more complex [example](https://beagle-playground-beta.netlify.app/#/cloud/1eae6a61c5514292bd8618c8bf1f92a8/main.json)

### Related issues

- [x] Web: https://github.com/ZupIT/beagle-web-core/issues/185
- [ ] Android: #539 
- [ ] iOS: #657

**Comment by Tiagoperes** [comment]
I don't have a full written proposal yet, but we can start discussing it. My idea is to implement a new concept on top of our expressions: **operations**.

As long as this proposal is accepted, we should no longer refer to the expressions as bindings, since these terms wouldn't be interchangeable anymore. Expressions would do more than simple bindings.

I viewed the problem through two different approaches:

- prefix: e.g. `condition(myVariable, 1, 2)`, `sum(myVariable, 5)`;
- and infix: e.g. `myVariable ? 1 : 2`, `myVariable + 5`;

The first approach (prefix) is much simpler to be implemented, much more scalable (we can come up with new operations as we wish without worrying about symbols) and developers are also used to it.

The second approach is more readable but brings complexity where, maybe, it is not needed. Also, if it becomes a necessity (I don't think it will), we could create an infix syntax on top of our prefix notation.

I decided to go with the first approach and basically, what we would be doing is allowing two more things inside our expressions:

- _Context bindings (we already have it)_
- **Literals**: strings (delimited by single quotes), numbers, true, false and null
- **Operations**: eq(..), condition(...), sum(...), subtract(...), gt(...), etc

For instance: `sum(counter, 2)`, `sum` is an operation, `counter` is a context binding and `2` is a literal.

When evaluating the expression, instead of just replacing a context value, we are going to evaluate the operations and literals to calculate the result.

This proposal is implemented in Beagle Web in a separate branch and it is online on Beagle Playground Beta, check an example [here](https://beagle-playground-beta.netlify.app/#/cloud/1eae6a61c5514292bd8618c8bf1f92a8/main.json).

I presented this to @tarcisiogc and he thinks it makes sense for Beagle. What do you all think? Should I elaborate a complete spec so we can implement this on every platform?

Another idea: operations are just functions, it would be extremely easy to create "custom operations". Is this something we want to do?

**Comment by Tiagoperes** [comment]
I'll give some more details about the solution here so we can discuss it better in the meeting later today. This will probably turn up to be the specification.

### Grammar
Our expressions today can have only one thing today: bindings, which are references to variables in the context. The new expressions proposed here can have `Binding`, `Operation` and `Literal`. See below a simple definition of the language:

In the code below, we use ``` to group symbols and `/` to represent regular expressions. `|` means "or".

```
Expression = @{Operation | Value}
Operation = Name(`Params | )`
Name = /\w[\w\d_]*/
Params = `Param,Param` | Param)
Param = Operation | Value
Value = Binding | Literal
Binding = /^(?!(true$|false$|null$|'|\d))\w([\w\d_]|(\[\d+\])|(\.[\w\d_]))*$/
Literal = String | Number | true | false | null
String = /^'([^'\\]|(\\.))*'$/
Number = /^\d+$/
```

Until now, beagle expressions were described by a regular grammar. By adding operations, the language becomes a bit more complex and it can't be represented by a regular grammar anymore, i.e. we can't use regular expressions to process them.

A proof that the new expression language is not regular is straight forward and there's no need to do it formally. Basically, to know when the parameters of an operation starts and when it ends, we need to count the number of parenthesis that have been opened and it is impossible to do it without any kind of memory.

The new language can be described by a context free grammar, i.e. we can recognize the language by using a Pushdown Deterministic Automaton (DPA) instead of only regular expressions. It is more complex to recognize these languages, but it shouldn't be very hard to implement.

A proof that the new expression language is context-free is that it was possible to build a DPA that recognizes it. The DPA is showed in the next session.

### Recognizing the new expressions

For a performance boost we can identify the expressions before trying to process them. If we just want to identify an expression we can use regular expressions. Once we recognize that an expression exists within the string, we can process it. For instance, `@{operation(abc}` is wrong, but when traversing the JSON we can recognize it as an expression and see that it's wrong only when parsing it. This is advantageous because by using a regular expression first, we don't need to run our DPA over the entire payload, but just on strings that might be a valid world of our language.

To recognize a candidate expression, we can use the following Deterministic Finite Automaton (DFA):

![DFA - candidate expression](https://i.ibb.co/K0jgJkh/expressions-Reconhecedor-de-express-es.png)

The DFA above can be translated o the following regular expression: `/@{(([^'\}]|('([^'\\]|\\.)*'))*)}/`.

Once we identified a candidate expression, we can begin to process it according to the language described in the previous section. We are interested only in the content between `@{` and `}`, i.e. the first capture group of the regex.

The following code was taken from the beagle-web implementation and is executed over the content of an expression. e.g. if the expression is `@{sum(counter, 1)}`, it will be executed over the string `sum(counter, 1)`.

```typescript
function evaluateExpression(expression: string, contextHierarchy: DataContext[]) {
  const literalValue = getLiteralValue(expression)
  if (literalValue) return literalValue

  const isOperation = expression.includes('(')
  if (isOperation) return getOperationValue(expression, contextHierarchy)

  // otherwise, it's a context binding
  return getBindingValue(expression, contextHierarchy)
}
```

The challenging part of the code above is `getOperationValue`. This function is responsible to parse the operation and execute it, i.e. we need to get the string we receive and, from it, determine what is the operation name and what is the list of parameters. See the example below:

`condition(lte(counter, 5), '<= 5', '> 5')``

we can use the regular expression `/^(\w[\w\d_]*)\((.*)\)$/` to separate the operation name from the parameter string:

```typescript
const match = "condition(lte(counter, 5), '<= 5', '> 5')".match(/^(\w[\w\d_]*)\((.*)\)$/)
const operationName = match[1]
const parameterList = match[2]
```

Our problem lies in `parameterList`. How to transform it into an array with each parameter for the operation? Since a parameter can be another operation, we can't do a simple `parameterList.split(',')`. We have to be able to count the parenthesis, which means, there's no regular expression to separate these parameters. We'll need at least a PDA to solve this problem.

We can use the following PDA to recognize a parameter inside a parameter list. Each time the final state is reached, a parameter has been recognized. The PDA must be executed until the end of `parameterList` is reached, each time a pattern is correctly identified, we should add the string identified to the array of parameters.

![DPA - parameters](https://i.ibb.co/ZY8FTrW/expressions-Reconhecedor-de-par-metros.png)

In the diagrams above, the first machine identifies a parameter inside the parameter string while the second just checks if it is inside a string. The second machine is a DFA and can be a regular expression when implementing.

With this we have all means to process everything. We just need to call `evaluateExpression` for each one of the parameters and after resolving all of them, execute the function referenced by the operation name.

### Important observations

- false, true, null, numbers and 'strings' are now literals and can't be used as context names. In practice, we need to throw an error every time a  context is named "true", "false", "null", starts with a number or has any character other than a letter, a number or an underline.
- literals can not be maps or arrays

### Probable problems in strongly typed languages:

 - Operations, as they have been proposed accepts any number of arguments. Examples: `sum(counter, 1)`, `sum(counter.a, counter.b, counter.c, 10)`.
- Operations accept any kind of literal: Examples: `sum(5, '5')` or `concat('teste', 10, 15, 'lol')`. Because web uses javascript, this is not a problem. How should beagle behave?
- The binding for an operation might be an object or array, what if the operation expected another type? Example: `sum(user, 5)`. Where `user` is a context with value `{ name: 'fulano', age: 32 }`.

**Comment by Tiagoperes** [comment]
Implementation: https://github.com/ZupIT/beagle-web-core/compare/feature/operations

**Comment by Tiagoperes** [comment]
Operations we should implement (this list is subject to change):

```typescript
interface Operations {
  sum: (...args: number[]): number,
  subtract: (...args: number[]): number,
  multiply: (...args: number[]): number,
  divide: (...args: number[]): number,
  condition: (premise: boolean, trueValue: any, falseValue: any): any,
  and: (...args: boolean[]): boolean,
  or: (...args: boolean[]): boolean,
  gt: (a: number, b: number): boolean,
  gte: (a: number, b: number): boolean,
  lt: (a: number, b: number): boolean,
  lte: (a: number, b: number): boolean,
  eq: (a: any, b: any): boolean,
  exists: (value: any): boolean,
  concat: (...args: string[]): string,
}
```

**Comment by carolinegoncalveszup** [comment]
Another operation that might be useful is an array union. We suggest `union(a: Array, b: Array) => Array`
One use case of the union operation proposed is an infinite scroll. The infinite scroll could be done combinating the union operation with the new list view definition which has the action onScrollEnd.

**Comment by Tiagoperes** [comment]
Attention: the operation suggested by @carolinegoncalveszup is necessary for the listview to work properly. It has been implemented in beagle-web as:

```typescript
union(...arrays: any[][]) => any[]
```

i.e. a function that receives any number of arrays and combine them in a single array by concatenating their elements in the order they appeared in the parameter list.

**Comment by Tiagoperes** [comment]
According to decisions took today, the following modifications must be done to this specification:

### default operation functions
- the operation `includes` must be renamed to `contains`

### operation and context names
- an operation can start with number, letter or `_`, i.e. operation names like `2sum` or `_sum` are valid. 
- the rules for context ids and operation names must be the same, please verify that context names can also start with number or `_`
- reminder: only letters, numbers and `_` are accepted as operation names or context ids
- reminder: numbers are not accepted as operations names or context ids. Example: a context cannot be called `58`, the same is true for an operation name.
- reminder: false, true and null are also not valid as operation names or context ids.
