### ISSUE TITLE
Backend/Android inconsistencies

### ISSUE THREAD

**Issue by vitorbassozup** [ZupIT/beagle#669]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
There are inconsistencies between the Android and Backend implementations. The examples I found were:
on Backend: class is named ImagePath / on Android: class is named PathType
On Backend: Bind.Expression constructor has only value as parameter / on Android: Bind.Expression constructor has value and type as parameters

## Steps To Reproduce
Check above classes both on their respective android and backend implementation

## Expected Results
Same signature

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by jefersonlopeszup** [comment]
PathType is a more suggestive name, since the variable is a type of path. However, if we change the backend we will end up creating break changes, so we will change it on the fronts. The method parameters are really different, the backend uses it to create the logic of the return of the path type, which can be both, justMobile or justWeb. The fronts do not need this logic, for receiving the Local or Remote directly.

**Comment by jefersonlopeszup** [comment]
PathType is a more suggestive name, since the variable is a type of path. However, if we change on the back end, we will end up with a break of changes, so we will change on the fronts. The parameters of the methods really are different, or the backend uses to create a path type return logic, which can be both, justMobile or justWeb. The fronts do not need this logic, to receive directly or Local or Remote.
