### ISSUE TITLE
ListView different behavior in IOS and Android

### ISSUE THREAD

**Issue by yandiaszup** [ZupIT/beagle#680]
## Description
ListView different behavior in IOS and Android when it has children with self layout flex attributes like margin.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Instantiate a screen like this:
```
let screen = Screen {
            ListView(direction: .vertical) {
                Text("oi")
                Text("oi", widgetProperties: WidgetProperties(style: Style(margin: EdgeValue().top(20))))
                Text("oi")
                Text("oi")
            }
}
```
## Results

IOS: 
![Screen Shot 2020-08-03 at 17 24 58](https://user-images.githubusercontent.com/42281214/89224085-4365eb00-d5ae-11ea-9ae8-ba7bac3ea7a7.png)

Android would appear like this: 
![Screen Shot 2020-08-03 at 17 25 59](https://user-images.githubusercontent.com/42281214/89224166-67293100-d5ae-11ea-8bda-4852121391e0.png)

## Conclusion

Whats happening its that ListView uses CollectionView as the scrolling component, and what tells the layout of a collection view its a collection view flow layout, not flex. 
We need to define what is the expected behavior in this case, and refactor one of the platforms

**Comment by yandiaszup** [comment]
Note that when we use a ScrollView in IOS we can use flex attributes in the scrollable content.
```
let screen = Screen {
            ScrollView(scrollDirection: .vertical) {
                Text("oi")
                Text("oi", widgetProperties: WidgetProperties(style: Style(margin: EdgeValue().top(20))))
                Text("oi")
                Text("oi")
            }
        }
```

![Screen Shot 2020-08-03 at 17 37 38](https://user-images.githubusercontent.com/42281214/89225079-07cc2080-d5b0-11ea-97a4-530855bf5cfc.png)

**Comment by theffc** [comment]
Currently, for most use cases we recommend using ScrollView instead of ListView, which will have a more consistent behavior right now.

That's because we are currently reimplementing how we handle ListView.  It will be a much better solution than what we have right now. A complete history of design decisions can be found at #210. It has been a really challenging solution because: every platform has a really different way to handle reuse of views, usage of Flex inside complex native List abstractions is not trivial, some edge cases like lists inside other lists can be tricky, and other beagle features need to work correctly with templates. But we think our solution is getting ready to be released, and so this bug will no longer happen.
